federation_version: 2
subgraphs:
  cms:
    routing_url: https://tapahtumat.app-staging.hkih.hion.dev/graphql
    # routing_url: https://tapahtumat.content.api.hel.fi/graphql
    # routing_url: https://harrastus.app-staging.hkih.hion.dev/graphql
    # routing_url: https://harrastus.content.api.hel.fi/graphql
    # routing_url: https://liikunta.app-staging.hkih.hion.dev/graphql
    # routing_url: https://liikunta.content.api.hel.fi/graphql
    schema:
      file: ./subgraphs/cms/cms.graphql
  events:
    routing_url: https://events-graphql-proxy.test.hel.ninja/proxy/graphql
    schema:
      file: ./subgraphs/events/events.graphql
  unified-search:
    routing_url: https://kuva-unified-search.api.test.hel.ninja/search
    schema:
      file: ./subgraphs/unified-search/unified-search.graphql
  venues:
    routing_url: https://venue-graphql-proxy.test.hel.ninja/proxy/graphql
    schema:
      file: ./subgraphs/venues/venues.graphql
