#
# Review pipeline. Run build and deploy for Platta test environments.
# Pipeline runs different tests e.g. unittest and browser tests.
#
# Continuous integration (CI) triggers cause a pipeline to run whenever you push
# an update to the specified branches or you push specified tags.
# only PR trigger pipeline
trigger: none

# Pull request (PR) triggers cause a pipeline to run whenever a pull request is
# opened with one of the specified target branches, or when updates are made to
# such a pull request.
#
# GitHub creates a new ref when a pull request is created. The ref points to a
# merge commit, which is the merged code between the source and target branches
# of the pull request.
#
# Opt out of pull request validation
pr:
  # PR target branch
  branches:
    include:
      - main
  paths:
    include:
      - 'apps/sports-helsinki/**'
      - 'packages/**'
      - 'package.json'
      - 'yarn.lock'
      - '.yarnrc.yml'
      - '*.base.json'
      - '*.base.js'
      - '.prettier*.*'
      - 'azure-pipelines-liikunta-review.yml'
      - 'Dockerfile'
      - '*.Dockerfile'
      - 'docker-compose.yml'
      - 'docker-compose.*.yml'
      - '!**/README.md'

# By default, use self-hosted agents
pool: Default

resources:
  repositories:
    # Azure DevOps repository
    - repository: liikunta-pipelines
      type: git
      # Azure DevOps project/repository
      name: liikunta/liikunta-pipelines

extends:
  # Filename in Azure DevOps Repository (note possible -ui or -api)
  # Django example: azure-pipelines-PROJECTNAME-api-release.yml
  # Drupal example: azure-pipelines-drupal-release.yml
  template: azure-pipelines-liikunta-review.yml@liikunta-pipelines
  parameters:
    # Application build arguments and config map values as key value pairs.
    # Does not contain all buildArguments, the rest located in liikunta-pipelines/liikunta-variables-development.yml and liikunta-variables-common.yml
    # The values here will override the values defined in the liikunta-pipelines repository
    buildArgs:
      FEDERATION_ROUTER_ENDPOINT: https://events-graphql-federation-sports.test.hel.ninja/
      CMS_ORIGIN: https://liikunta.hkih.stage.geniem.io
      LINKEDEVENTS_EVENT_ENDPOINT: https://linkedevents.api.test.hel.ninja/v1/event
      NEXTJS_DISABLE_SENTRY: 1
      NEXT_PUBLIC_ALLOW_UNAUTHORIZED_REQUESTS: 1
      NEXT_PUBLIC_DEBUG: 1
      NEXT_PUBLIC_MATOMO_ENABLED: 0
    configMap: # pod environment variables
      FEDERATION_ROUTER_ENDPOINT: https://events-graphql-federation-sports.test.hel.ninja/
      CMS_ORIGIN: https://liikunta.hkih.stage.geniem.io
      LINKEDEVENTS_EVENT_ENDPOINT: https://linkedevents.api.test.hel.ninja/v1/event
