#
# Test pipeline. Run build and deploy for Platta test environments.
# Pipeline runs different tests e.g. unittest and browser tests.
#
# Continuous integration (CI) triggers cause a pipeline to run whenever you push
# an update to the specified branches or you push specified tags.
trigger:
  batch: true
  branches:
    include:
      - main
  paths:
    include:
      - 'proxies/events-graphql-federation/**'
      - 'azure-pipelines-liikunta-federation-router-test.yml'
      - '!**/README.md'
      - '!**/CHANGELOG.md'
      - '!**/LICENSE'
      - '!**/.env*'
      - '!**/docker-compose*'

# Pull request (PR) triggers cause a pipeline to run whenever a pull request is
# opened with one of the specified target branches, or when updates are made to
# such a pull request.
#
# GitHub creates a new ref when a pull request is created. The ref points to a
# merge commit, which is the merged code between the source and target branches
# of the pull request.
#
# Opt out of pull request validation
pr: none

# By default, use self-hosted agents
pool: Default

# Image tag name for Fuse projects
#parameters:
#- name: imagetag
#  displayName: Image tag to be built and/or deployed
#  type: string
#  default: latest

resources:
  repositories:
    # Azure DevOps repository
    - repository: liikunta-pipelines
      type: git
      # Azure DevOps project/repository
      name: liikunta/liikunta-pipelines

extends:
  # Filename in Azure DevOps Repository (note possible -ui or -api)
  # Django example: azure-pipelines-PROJECTNAME-api-release.yml
  # Drupal example: azure-pipelines-drupal-release.yml
  template: azure-pipelines-federation-router-test.yml@liikunta-pipelines
  parameters:
    # Application build arguments and config map values as key value pairs.
    # Does not contain all buildArguments, the rest located in liikunta-pipelines/federation-router-variables-testing.yml and federation-router-variables-common.yml
    # The values here will override the values defined in the liikunta-pipelines repository
    # buildArgs: no buildArgs
    configMap: # pod environment variables
      FEDERATION_CMS_ROUTING_URL: https://liikunta.hkih.stage.geniem.io/graphql
      FEDERATION_UNIFIED_SEARCH_ROUTING_URL: https://kuva-unified-search.api.test.hel.ninja/search
      FEDERATION_EVENTS_ROUTING_URL: https://events-graphql-proxy.test.hel.ninja/proxy/graphql
      FEDERATION_VENUES_ROUTING_URL: https://venue-graphql-proxy.test.hel.ninja/proxy/graphql
