version: '3.9'
services:
  events-graphql-proxy:
    container_name: events-graphql-proxy
    build:
      context: .
      dockerfile: proxy.Dockerfile
      target: develop
      args:
        - PROXY=events-graphql-proxy
        - GRAPHQL_PROXY_PORT=${GRAPHQL_PROXY_PORT}
    environment:
      - GRAPHQL_PROXY_DEBUG=${GRAPHQL_PROXY_DEBUG}
      - GRAPHQL_PROXY_API_BASE_URL=${GRAPHQL_PROXY_API_BASE_URL}
      - GRAPHQL_PROXY_MAP_OPEN_DATA_API_BASE_URL=${GRAPHQL_PROXY_MAP_OPEN_DATA_API_BASE_URL}
      - GRAPHQL_PROXY_SENTRY_DSN=${GRAPHQL_PROXY_SENTRY_DSN}
      - GRAPHQL_PROXY_SENTRY_ENVIRONMENT=${GRAPHQL_PROXY_SENTRY_ENVIRONMENT}
      - GRAPHQL_PROXY_DISABLE_WINSTON_LOGGING=${GRAPHQL_PROXY_DISABLE_WINSTON_LOGGING}
        GRAPHQL_PROXY_INTROSPECTION=${GRAPHQL_PROXY_INTROSPECTION}
      - GRAPHQL_PROXY_PORT=${GRAPHQL_PROXY_PORT}
    ports:
      - ${GRAPHQL_PROXY_PORT}:${GRAPHQL_PROXY_PORT}
