version: '3.9'
services:
  events-graphql-proxy:
    container_name: events-graphql-proxy
    build:
      context: .
      dockerfile: proxy.Dockerfile
      target: develop
      args:
        - PROXY=events-graphql-proxy
    environment:
      - GRAPHQL_PROXY_DEBUG=${GRAPHQL_PROXY_DEBUG}
      - GRAPHQL_PROXY_API_BASE_URL=${GRAPHQL_PROXY_API_BASE_URL}
      - GRAPHQL_PROXY_SENTRY_DSN=${GRAPHQL_PROXY_SENTRY_DSN}
      - GRAPHQL_PROXY_SENTRY_ENVIRONMENT=${GRAPHQL_PROXY_SENTRY_ENVIRONMENT}
    ports:
      - 4100:4100
