version: '3.9'
services:
  # Start events in development
  # docker-compose -f docker-compose.events.yml up develop
  develop:
    container_name: events-helsinki-develop
    # profiles:
    #   - donotstart
    stdin_open: true
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
    build:
      context: .
      dockerfile: Dockerfile
      target: develop
      args:
        APP_PORT: 3000
        PROJECT: events-helsinki
    volumes:
      # Share the source code to allow development
      - .:/app/
      # Prevent sharing of node_modules between host and container
      # to avoid ownership and/or platform issues
      - build_events-helsinki:/app/apps/events-helsinki/.next
      - nm_events-helsinki:/app/node_modules

  # Convenience production "deps" stage service for debugging
  # Build > docker buildx bake -f docker-compose.events-helsinki.yml --progress: tty deps
  deps:
    container_name: events-helsinki-multistage-deps
    # profiles:
    #   - donotstart
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
      target: deps
      args:
        PROJECT: events-helsinki
  # Convenience production "builder" stage service for debugging
  # Build > docker buildx bake -f docker-compose.events-helsinki.yml --progress=tty runner
  builder:
    container_name: events-helsinki-multistage-builder
    # profiles:
    #   - donotstart
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
      args:
        - APP_PORT=3000
        - PROJECT=events-helsinki

  # Convenience production "cache" stage service for debugging
  # Build > docker buildx bake -f docker-compose.events.yml --progress=tty cache
  # Build > docker compose -f docker-compose.events.yml build --progress=tty cache
  cache:
    container_name: events-helsinki-multistage-cache
    # profiles:
    #   - donotstart
    stdin_open: true
    build:
      context: .
      dockerfile: DockerfileCache
      target: cache
      args:
        - APP_PORT=3000
        - PROJECT=events-helsinki

  # Convenience production "runner" stage service for debugging
  # Build > docker buildx bake -f docker-compose.events-helsinki.yml --progress=tty runner
  # Run   > docker-compose -f docker-compose.events-helsinki.yml --env-file ./apps/events-helsinki/.env.local up runner
  runner:
    container_name: events-helsinki-multistage-runner
    # profiles:
    #   - donotstart
    stdin_open: false
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
      args:
        - APP_PORT=3000
        - PROJECT=events-helsinki
        - DOCKER_NEXTJS_DISABLE_SENTRY=true
        - NEXTJS_DISABLE_SENTRY=true
        - SENTRY_AUTH_TOKEN
        - NEXT_PUBLIC_FEDERATION_ROUTER_ENDPOINT
        - NEXT_PUBLIC_CMS_ORIGIN
        - NEXT_PUBLIC_LINKEDEVENTS_EVENT_ENDPOINT
        - NEXT_PUBLIC_APP_ORIGIN
        - NEXT_PUBLIC_MATOMO_URL_BASE
        - NEXT_PUBLIC_MATOMO_SITE_ID
        - NEXT_PUBLIC_MATOMO_SRC_URL
        - NEXT_PUBLIC_MATOMO_TRACKER_URL
        - NEXT_PUBLIC_MATOMO_ENABLED
        - NEXT_PUBLIC_ASKEM_API_KEY_FI
        - NEXT_PUBLIC_ASKEM_API_KEY_EN
        - NEXT_PUBLIC_ASKEM_API_KEY_SV
        - NEXT_PUBLIC_ASKEM_ENABLED
        - NEXT_PUBLIC_ALLOW_UNAUTHORIZED_REQUESTS
        - NEXT_PUBLIC_SENTRY_ENVIRONMENT
        - NEXT_PUBLIC_SENTRY_DSN
        - NEXT_PUBLIC_SENTRY_TRACE_SAMPLE_RATE
        - NEXT_PUBLIC_DEBUG
        - NEXT_PUBLIC_IMAGE_PROXY_URL
        - NEXT_PUBLIC_DEFAULT_ISR_REVALIDATE_SECONDS
        - NEXT_PUBLIC_CMS_HEADER_MENU_NAME_FI
        - NEXT_PUBLIC_CMS_HEADER_MENU_NAME_EN
        - NEXT_PUBLIC_CMS_HEADER_MENU_NAME_SV
        - NEXT_PUBLIC_CMS_FOOTER_MENU_NAME_FI
        - NEXT_PUBLIC_CMS_FOOTER_MENU_NAME_EN
        - NEXT_PUBLIC_CMS_FOOTER_MENU_NAME_SV
        - NEXT_PUBLIC_CMS_ARTICLES_CONTEXT_PATH
        - NEXT_PUBLIC_CMS_PAGES_CONTEXT_PATH
volumes:
  build_events-helsinki:
  nm_events-helsinki:
