services:
  apollo-router:
    container_name: events-graphql-federation
    build:
      context: ./proxies/events-graphql-federation/
      dockerfile: Dockerfile
      target: develop

    environment:
      - FEDERATION_CMS_ROUTING_URL=${FEDERATION_CMS_ROUTING_URL}
      - FEDERATION_EVENTS_ROUTING_URL=${FEDERATION_EVENTS_ROUTING_URL:-https://events-graphql-proxy.test.hel.ninja/proxy/graphql}
      - FEDERATION_UNIFIED_SEARCH_ROUTING_URL=${FEDERATION_UNIFIED_SEARCH_ROUTING_URL:-https://kuva-unified-search.api.test.hel.ninja/search}
      - FEDERATION_VENUES_ROUTING_URL=${FEDERATION_VENUES_ROUTING_URL:-https://venue-graphql-proxy.test.hel.ninja/proxy/graphql}
    ports:
      - '4000:4000'
      - '8088:8088'
