version: '3'
services:
  apollo-router:
    container_name: events-graphql-proxy
    build:
      context: ./proxies/events-graphql-proxy/
      dockerfile: Dockerfile
      target: develop

    environment:
      - GRAPHQL_PROXY_DEBUG=${GRAPHQL_PROXY_DEBUG}
      - GRAPHQL_PROXY_PORT=${GRAPHQL_PROXY_PORT}
      - GRAPHQL_PROXY_ENGINE_API_KEY=${GRAPHQL_PROXY_ENGINE_API_KEY}
      - GRAPHQL_PROXY_CMS_API_BASE_URL=${GRAPHQL_PROXY_CMS_API_BASE_URL}
      - GRAPHQL_PROXY_API_BASE_URL=${GRAPHQL_PROXY_API_BASE_URL}
      - GRAPHQL_PROXY_SENTRY_DSN=${GRAPHQL_PROXY_SENTRY_DSN}
      - GRAPHQL_PROXY_SENTRY_ENVIRONMENT=${GRAPHQL_PROXY_SENTRY_ENVIRONMENT}
    ports:
      - '4100:4100'
