version: '3'
services:
  apollo-router:
    container_name: events-graphql-federation
    build:
      context: ./proxies/events-graphql-federation/
      dockerfile: Dockerfile
      target: develop

    environment:
      - FEDERATION_CMS_ROUTING_URL=${FEDERATION_CMS_ROUTING_URL}
      - FEDERATION_EVENTS_ROUTING_URL=${FEDERATION_EVENTS_ROUTING_URL:-https://tapahtumat-proxy.test.kuva.hel.ninja/proxy/graphql}
      - FEDERATION_UNIFIED_SEARCH_ROUTING_URL=${FEDERATION_UNIFIED_SEARCH_ROUTING_URL:-https://unified-search.test.kuva.hel.ninja/search}
      - FEDERATION_VENUES_ROUTING_URL=${FEDERATION_VENUES_ROUTING_URL:-http://host.docker.internal:3000/api/graphql}
    ports:
      - '4000:4000'
      - '8088:8088'
