sonar.projectKey = City-of-Helsinki_venue-graphql-proxy
sonar.organization=city-of-helsinki
sonar.javascript.lcov.reportPaths=./coverage/lcov.info
sonar.sourceEncoding=UTF-8
sonar.sources=src
sonar.exclusions= **/__generated__*

sonar.test.inclusions= \
  **/__tests__/**/*, \
  **/*.test.js, \
  **/*.test.ts, \
  **/*.test.jsx, \
  **/*.test.tsx

sonar.coverage.exclusions= \
  src/index.ts, \
  src/config/AppConfig.ts, \
  src/schema/**/typeDefs.ts, \
  src/schema/**/paginationSchema.ts, \
  src/contants/constants.ts, \
  src/types/**
