const i18nRootPaths = ['/fi/pages', '/fi/sivut'];

const redirectRoutes = i18nRootPaths.reduce((result, langPageRoot) => {
  // Ignore prettier in order to preserve readability of the routes]:
  // prettier-ignore
  return {
    ...result,
    [`${langPageRoot}/liikuntapalvelut/seniorisapinat`]: '/fi/sivut/kohderyhmat/ikaantyneet/seniorisapinat',
    [`${langPageRoot}/liikuntapalvelut/easysport`]: '/fi/sivut/kohderyhmat/lapset-ja-perheet/easysport',
    [`${langPageRoot}/liikuntapalvelut/easysport/easysportin-yhteistyotahot`]: '/fi/sivut/kohderyhmat/lapset-ja-perheet/easysport/easysportin-yhteistyotahot',
    [`${langPageRoot}/liikuntapalvelut/ohjattu-liikunta/lasten-uimakoulut`]: '/fi/sivut/kohderyhmat/lapset-ja-perheet/lasten-uimakoulut',
    [`${langPageRoot}/liikuntapalvelut/liikuntahulinat`]: '/fi/sivut/kohderyhmat/lapset-ja-perheet/liikuntahulinat',
    [`${langPageRoot}/liikuntapalvelut/perhehulinat-omatoiminen`]: '/fi/sivut/kohderyhmat/lapset-ja-perheet/perhehulinat-omatoiminen',
    [`${langPageRoot}/liikuntapalvelut/funaction`]: '/fi/sivut/kohderyhmat/nuoret/funaction',
    [`${langPageRoot}/liikuntapalvelut/funaction/yhteystyoseurat`]: '/fi/sivut/kohderyhmat/nuoret/funaction/yhteistyoseurat',
    [`${langPageRoot}/liikuntapalvelut/nyt-liikunta`]: '/fi/sivut/kohderyhmat/nuoret/nyt-liikunta',
    [`${langPageRoot}/liikuntapalvelut/nyt-liikunta/yhteistyoseurat`]: '/fi/sivut/kohderyhmat/nuoret/nyt-liikunta/yhteistyoseurat',
    [`${langPageRoot}/kohderyhmat/kumppanit/liikuntatilojen-varaaminen`]: '/fi/sivut/liikuntatilojen-varaaminen',
    [`${langPageRoot}/kohderyhmat/kumppanit/liikuntatilojen-varaaminen/helsingin-kaupungin-koulujen-liikuntasalien-vapaa-ajan-kaytto`]: '/fi/sivut/liikuntatilojen-varaaminen/helsingin-kaupungin-koulujen-liikuntasalien-vapaa-ajan-kaytto',
    [`${langPageRoot}/kohderyhmat/kumppanit/liikuntatilojen-varaaminen/koulujen-liikuntasalien-itsenainen-kaytto`]: '/fi/sivut/liikuntatilojen-varaaminen/koulujen-liikuntasalien-itsenainen-kaytto',
    [`${langPageRoot}/kohderyhmat/kumppanit/liikuntatilojen-varaaminen/ohjeet-vuorojen-hakemiseen`]: '/fi/sivut/liikuntatilojen-varaaminen/ohjeet-vuorojen-hakemiseen',
    [`${langPageRoot}/kohderyhmat/kumppanit/liikuntatilojen-varaaminen/ohjeet-vuorojen-hakemiseen/ohjeet-vuorojen-hakemiseen`]: '/fi/sivut/liikuntatilojen-varaaminen/ohjeet-vuorojen-hakemiseen/ohjeet-vuorojen-hakemiseen',
    [`${langPageRoot}/kohderyhmat/kumppanit/liikuntatilojen-varaaminen/ohjeet-vuorojen-hakemiseen/liikuntapalvelun-tilojen-ja-koulujen-liikuntasalien-sopimusehdot/omavalvontaliikuntasalien-sopimusehdot`]: '/fi/sivut/liikuntatilojen-varaaminen/ohjeet-vuorojen-hakemiseen/liikuntapalvelun-tilojen-ja-koulujen-liikuntasalien-sopimusehdot/omavalvontaliikuntasalien-sopimusehdot',
    [`${langPageRoot}/kohderyhmat/kumppanit/liikuntatilojen-varaaminen/ohjeet-vuorojen-hakemiseen/liikuntapalvelun-tilojen-ja-koulujen-liikuntasalien-sopimusehdot/kaisaniemenkentan-peruutusehdot`]: '/fi/sivut/liikuntatilojen-varaaminen/ohjeet-vuorojen-hakemiseen/liikuntapalvelun-tilojen-ja-koulujen-liikuntasalien-sopimusehdot/kaisaniemenkentan-peruutusehdot',
    [`${langPageRoot}/kohderyhmat/kumppanit/liikuntatilojen-varaaminen/ohjeet-vuorojen-hakemiseen/liikuntapalvelun-tilojen-ja-koulujen-liikuntasalien-sopimusehdot/vakiovuorojen-sopimusehdot`]: '/fi/sivut/liikuntatilojen-varaaminen/ohjeet-vuorojen-hakemiseen/liikuntapalvelun-tilojen-ja-koulujen-liikuntasalien-sopimusehdot/vakiovuorojen-sopimusehdot',
    [`${langPageRoot}/kohderyhmat/kumppanit/liikuntatilojen-varaaminen/ohjeet-vuorojen-hakemiseen/liikuntapalvelun-tilojen-ja-koulujen-liikuntasalien-sopimusehdot/yksittaisvuorojen-seka-tapahtumien-sopimus-ja-peruutusehdot`]: '/fi/sivut/liikuntatilojen-varaaminen/ohjeet-vuorojen-hakemiseen/liikuntapalvelun-tilojen-ja-koulujen-liikuntasalien-sopimusehdot/yksittaisvuorojen-seka-tapahtumien-sopimus-ja-peruutusehdot',
    [`${langPageRoot}/kohderyhmat/kumppanit/liikuntatilojen-varaaminen/ohjeet-vuorojen-hakemiseen/ohjeet-vaalitilaisuuden-tilavaraukseen`]: '/fi/sivut/liikuntatilojen-varaaminen/ohjeet-vuorojen-hakemiseen/ohjeet-vaalitilaisuuden-tilavaraukseen',
    [`${langPageRoot}/kohderyhmat/kumppanit/liikuntatilojen-varaaminen/ohjeet-vuorojen-hakemiseen/sahkoisen-asioinnin-ohjeet`]: '/fi/sivut/liikuntatilojen-varaaminen/ohjeet-vuorojen-hakemiseen/sahkoisen-asioinnin-ohjeet',
    [`${langPageRoot}/kohderyhmat/kumppanit/liikuntatilojen-varaaminen/vuorojenjakokriteerit`]: '/fi/sivut/liikuntatilojen-varaaminen/vuorojenjakokriteerit',
    [`${langPageRoot}/liikuntapalvelut/maksut-ja-hinnasto`]: '/fi/sivut/maksut-ja-hinnasto',
    [`${langPageRoot}/liikuntapalvelut/maksut-ja-hinnasto/hintaryhmien-maarittely`]: '/fi/sivut/maksut-ja-hinnasto/hintaryhmien-maarittely',
    [`${langPageRoot}/liikuntapalvelut/maksut-ja-hinnasto/ladattava-asiakaskortti`]: '/fi/sivut/maksut-ja-hinnasto/ladattava-asiakaskortti',
    [`${langPageRoot}/liikuntapalvelut/maksut-ja-hinnasto/ladattava-asiakaskortti/ladattavan-asiakaskortin-sopimusehdot`]: '/fi/sivut/maksut-ja-hinnasto/ladattava-asiakaskortti/ladattavan-asiakaskortin-sopimusehdot',
    [`${langPageRoot}/liikuntapalvelut/maksut-ja-hinnasto/liikuntasetelit`]: '/fi/sivut/maksut-ja-hinnasto/liikuntasetelit',
    [`${langPageRoot}/liikuntapalvelut/maaraykset-ja-ohjeet`]: '/fi/sivut/maaraykset-ja-ohjeet',
    [`${langPageRoot}/liikuntapalvelut/maaraykset-ja-ohjeet/ekokompassi`]: '/fi/sivut/maaraykset-ja-ohjeet/ekokompassi',
    [`${langPageRoot}/liikuntapalvelut/maaraykset-ja-ohjeet/liikuntapaikkojen-yleiset-jarjestyssaannot`]: '/fi/sivut/maaraykset-ja-ohjeet/liikuntapaikkojen-yleiset-jarjestyssaannot',
    [`${langPageRoot}/liikuntapalvelut/maaraykset-ja-ohjeet/liikuntasalien-yleiset-jarjestyssaannot`]: '/fi/sivut/maaraykset-ja-ohjeet/liikuntasalien-yleiset-jarjestyssaannot',
    [`${langPageRoot}/liikuntapalvelut/maaraykset-ja-ohjeet/uima-allastilojen-hygienia`]: '/fi/sivut/maaraykset-ja-ohjeet/uima-allastilojen-hygienia',
    [`${langPageRoot}/liikuntapalvelut/maaraykset-ja-ohjeet/uima-allastilojen-hygienia/uima-allastilojen-hygienian-valvonta`]: '/fi/sivut/maaraykset-ja-ohjeet/uima-allastilojen-hygienia/uima-allastilojen-hygienian-valvonta',
    [`${langPageRoot}/liikuntapalvelut/maaraykset-ja-ohjeet/uimahallien-ja-uimaloiden-yleiset-jarjestyssaannot`]: '/fi/sivut/maaraykset-ja-ohjeet/uimahallien-ja-uimaloiden-yleiset-jarjestyssaannot',
    [`${langPageRoot}/liikuntapalvelut/maaraykset-ja-ohjeet/uimapukuohjeistus-helsingin-kaupungin-uimahalleissa`]: '/fi/sivut/maaraykset-ja-ohjeet/uimapukuohjeistus-helsingin-kaupungin-uimahalleissa',
    [`${langPageRoot}/liikuntapalvelut/maaraykset-ja-ohjeet/uimarantojen-ulkoiluohje`]: '/fi/sivut/maaraykset-ja-ohjeet/uimarantojen-ulkoiluohje',
    [`${langPageRoot}/liikuntapalvelut/ohjattu-liikunta`]: '/fi/sivut/ohjattu-liikunta',
    [`${langPageRoot}/liikuntapalvelut/ohjattu-liikunta/soveltavat-ryhmat`]: '/fi/sivut/ohjattu-liikunta/soveltavat-ryhmat',
    [`${langPageRoot}/liikuntapalvelut/ohjattu-liikunta/aikuisten-liikuntakurssit`]: '/fi/sivut/ohjattu-liikunta/aikuisten-liikuntakurssit',
    [`${langPageRoot}/liikuntapalvelut/alueliikunta`]: '/fi/sivut/ohjattu-liikunta/alueliikunta',
    [`${langPageRoot}/liikuntapalvelut/alueliikunta/jakomaki-ja-tapulikaupunki`]: '/fi/sivut/ohjattu-liikunta/alueliikunta/jakomaki-ja-tapulikaupunki',
    [`${langPageRoot}/liikuntapalvelut/alueliikunta/kaarelan-alue-ja-maunula`]: '/fi/sivut/ohjattu-liikunta/alueliikunta/kaarelan-alue-ja-maunula',
    [`${langPageRoot}/liikuntapalvelut/alueliikunta/mellunkylan-alue`]: '/fi/sivut/ohjattu-liikunta/alueliikunta/mellunkylan-alue',
    [`${langPageRoot}/liikuntapalvelut/alueliikunta/vuosaaren-alue`]: '/fi/sivut/ohjattu-liikunta/alueliikunta/vuosaaren-alue',
    [`${langPageRoot}/liikuntapalvelut/ohjattu-liikunta/ikaantyneiden-liikuntakurssit`]: '/fi/sivut/ohjattu-liikunta/ikaantyneiden-liikuntakurssit',
    [`${langPageRoot}/liikuntapalvelut/ohjattu-liikunta/ilmoittautuminen-liikuntakursseille/`]: '/fi/sivut/ohjattu-liikunta/ilmoittautuminen-liikuntakursseille',
    [`${langPageRoot}/liikuntapalvelut/ohjattu-liikunta/kurssitoiminnan-asiakassopimusehdot/`]: '/fi/sivut/ohjattu-liikunta/kurssitoiminnan-asiakassopimusehdot',
    [`${langPageRoot}/liikuntapalvelut/ohjattu-liikunta/lasten-soveltavat-liikuntakurssit`]: '/fi/sivut/ohjattu-liikunta/lasten-soveltavat-liikuntakurssit',
    [`${langPageRoot}/liikuntapalvelut/ohjattu-liikunta/lasten-nuorten-ja-perheiden-liikuntakurssit`]: '/fi/sivut/ohjattu-liikunta/lasten-nuorten-ja-perheiden-liikuntakurssit',
    [`${langPageRoot}/liikuntapalvelut/ohjattu-liikunta/liikuntakurssien-tuntikuvaukset`]: '/fi/sivut/ohjattu-liikunta/liikuntakurssien-tuntikuvaukset',
    [`${langPageRoot}/liikuntapalvelut/ohjattu-liikunta/puistojumpat`]: '/fi/sivut/ohjattu-liikunta/puistojumpat',
    [`${langPageRoot}/liikuntapalvelut/ohjattu-liikunta/svensksprakiga-verksamheten`]: '/fi/sivut/ohjattu-liikunta/svensksprakiga-verksamheten',
    [`${langPageRoot}/liikuntapalvelut`]: '/fi',
    [`${langPageRoot}/liikuntapalvelut/erityisuimakortti`]: '/fi/sivut/tukea-liikkumiseen/erityisuimakortti',
    [`${langPageRoot}/liikuntapalvelut/erityisuimakortti/ukk-erityisuimakortti`]: '/fi/sivut/tukea-liikkumiseen/erityisuimakortti/ukk-erityisuimakortti',
    [`${langPageRoot}/liikuntapalvelut/kuntosaliohjelmien-laadinta-ja-opastus`]: '/fi/sivut/tukea-liikkumiseen/kuntosaliohjelmien-laadinta-ja-opastus',
    [`${langPageRoot}/liikuntapalvelut/kuntotestaus`]: '/fi/sivut/tukea-liikkumiseen/kuntotestaus',
    [`${langPageRoot}/liikuntapalvelut/liikkumisohjelma`]: '/fi/sivut/tukea-liikkumiseen/liikkumisohjelma',
    [`${langPageRoot}/liikuntapalvelut/liikuntaluuri`]: '/fi/sivut/tukea-liikkumiseen/liikuntaluuri',
    [`${langPageRoot}/liikuntapalvelut/liikuntaneuvonta`]: '/fi/sivut/tukea-liikkumiseen/liikuntaneuvonta',
    [`${langPageRoot}/liikuntapalvelut/liikuntaneuvonta/harrastusstartti-funaction`]: '/fi/sivut/tukea-liikkumiseen/liikuntaneuvonta/harrastusstartti-funaction',
    [`${langPageRoot}/liikuntapalvelut/liikuntaneuvonta/ikaantyneiden-liikuntaneuvonta-yli-64-vuotiaat`]: '/fi/sivut/tukea-liikkumiseen/liikuntaneuvonta/ikaantyneiden-liikuntaneuvonta-yli-64-vuotiaat',
    [`${langPageRoot}/liikuntapalvelut/liikuntaneuvonta/koulupt-toiminta-liikuntaneuvontaa-13-17-vuotiaille-nuorille`]: '/fi/sivut/tukea-liikkumiseen/liikuntaneuvonta/koulupt-toiminta-liikuntaneuvontaa-13-17-vuotiaille-nuorille',
    [`${langPageRoot}/liikuntapalvelut/liikuntaneuvonta/liikuntaneuvonta-aikuisille-30-63-vuotiaat`]: '/fi/sivut/tukea-liikkumiseen/liikuntaneuvonta/liikuntaneuvonta-aikuisille-30-63-vuotiaat',
    [`${langPageRoot}/liikuntapalvelut/liikuntaneuvonta/liikuntaneuvonta-16-29-vuotiaille-nuorille-ja-nuorille-aikuisille`]: '/fi/sivut/tukea-liikkumiseen/liikuntaneuvonta/liikuntaneuvonta-16-29-vuotiaille-nuorille-ja-nuorille-aikuisille',
    [`${langPageRoot}/liikuntapalvelut/liikuntaneuvonta/soveltava-liikuntaneuvonta`]: '/fi/sivut/tukea-liikkumiseen/liikuntaneuvonta/soveltava-liikuntaneuvonta',
    [`${langPageRoot}/liikuntapalvelut/vapaaehtoistoiminta-liikuntapalveluissa`]: '/fi/sivut/tukea-liikkumiseen/vapaaehtoistoiminta-liikuntapalveluissa',
    [`${langPageRoot}/liikuntapalvelut/vapaaehtoistoiminta-liikuntapalveluissa/liikuntaluotsi`]: '/fi/sivut/tukea-liikkumiseen/vapaaehtoistoiminta-liikuntapalveluissa/liikuntaluotsi'
  }
}, {});

module.exports = redirectRoutes;
