// Ignore prettier in order to preserve readability of the routes:
// prettier-ignore
const redirectRoutes = {
  // Finnish locale versions
  '/ulkokuntosaliohjaukset': '/fi/pages/ohjattu-liikunta/ohjattu-toiminta-ulkokuntosaleilla',
  '/yhdessaulkokuntosalille': '/fi/articles/yleinen/yhdessa-ulkokuntosalille-maksutonta-ulkokuntosaliohjausta-kolmena-perjantaina-toukokuussa',
  '/kirjastoliikunta': '/fi/articles/yleinen/kirjastoliikunta',
  '/lapset-ja-perheet': '/fi/pages/kohderyhmat/lapset-ja-perheet',
  '/nuoret': '/fi/pages/kohderyhmat/nuoret',
  '/aikuiset': '/fi/pages/kohderyhmat/aikuiset',
  '/ikaantyneet': '/fi/pages/kohderyhmat/ikaantyneet',
  '/soveltavat-ryhmat': '/fi/pages/kohderyhmat/soveltavat-ryhmat',
  '/kumppanit': '/fi/pages/kohderyhmat/kumppanit',
  '/easysport': '/fi/pages/kohderyhmat/lapset-ja-perheet/easysport',
  '/vimmaliikunta': '/fi/pages/kohderyhmat/nuoret/vimma-liikunta',
  '/funaction': '/fi/pages/kohderyhmat/nuoret/vimma-liikunta',
  '/pages/kohderyhmat/nuoret/funaction': '/fi/pages/kohderyhmat/nuoret/vimma-liikunta',
  '/nytliikunta': '/fi/pages/kohderyhmat/nuoret/nyt-liikunta',
  '/alueliikunta': '/fi/pages/ohjattu-liikunta/alueliikunta',
  '/ohjattu-liikunta': '/fi/pages/ohjattu-liikunta/alueliikunta',
  '/puistojumpat': '/fi/pages/ohjattu-liikunta/puistojumpat',
  '/seniorisapinat': '/fi/pages/kohderyhmat/ikaantyneet/seniorisapinat',
  '/erityisuimakortti': '/fi/pages/tukea-liikkumiseen/erityisuimakortti',
  '/kuntotestaus': '/fi/pages/tukea-liikkumiseen/kuntotestaus',
  '/kuntosaliohjelmat': '/fi/pages/tukea-liikkumiseen/kuntosaliohjelmien-laadinta-ja-opastus',
  '/liikuntaneuvonta': '/fi/pages/tukea-liikkumiseen/liikuntaneuvonta',
  '/liikuntaluuri': '/fi/pages/tukea-liikkumiseen/liikuntaluuri',
  '/liikuntahulinat': '/fi/pages/kohderyhmat/lapset-ja-perheet/liikuntahulinat',
  '/perhehulinat': '/fi/pages/kohderyhmat/lapset-ja-perheet/perhehulinat-omatoiminen',
  '/liikuntatilavaraukset': '/fi/pages/liikuntatilojen-varaaminen',
  '/maksut': '/fi/pages/maksut-ja-hinnasto',
  // Swedish locale versions
  '/biblioteks-motion': '/sv/articles/aldre/gor-motion-till-en-rutin-i-ditt-liv-delta-i-biblioteksmotionen-for-aldre-manniskor',
  '/barn-och-familjer': '/sv/sidor/malgrupper/barn-och-familjer',
  '/unga': '/sv/pages/malgrupper/unga',
  '/vuxna': '/sv/pages/malgrupper/vuxna',
  '/aldre': '/sv/pages/malgrupper/aldre',
  '/tillampade-grupper': '/sv/pages/malgrupper/tillampande-grupper',
  '/partners': '/sv/pages/malgrupper/partners',
  '/easysport/sv': '/sv/pages/malgrupper/barn-och-familjer/easysport',
  '/vimmamotion/sv': '/sv/pages/malgrupper/unga/vimma-motion/',
  '/funaction/sv': '/sv/pages/malgrupper/unga/vimma-motion/',
  '/pages/malgrupper/unga/funaction': '/sv/pages/malgrupper/unga/vimma-motion/',
  '/nyt-motion': '/sv/pages/malgrupper/unga/nyt-motion',
  '/forortsmotion': '/sv/pages/handledd-motion/forortsmotion',
  '/handledd-motion': '/sv/pages/handledd-motion',
  '/parkgymnastiken': '/sv/pages/handledd-motion/parkgymnastiken',
  '/seniorisapinat/sv': '/sv/pages/malgrupper/aldre/seniorisapinat',
  '/specialsimkort': '/sv/pages/stod-for-motion/specialsimkort',
  '/konditionstest': '/sv/pages/stod-for-motion/konditionstest',
  '/gymprogram': '/sv/pages/stod-for-motion/handledning-och-utarbetande-av-ett-gymprogram',
  '/motionsradgivning': '/sv/pages/stod-for-motion/motionsradgivning',
  '/motionsluren': '/sv/pages/stod-for-motion/liikuntaluuri-motionsluren',
  '/idrottslek': '/sv/pages/malgrupper/barn-och-familjer/liikuntahulinat-idrottslek',
  '/idrottslek-for-familjer': '/sv/pages/malgrupper/barn-och-familjer/perhehulinat-idrottslek-for-familjer-pa-egen-hand',
  '/bokning-av-idrottsutrymmen': '/sv/pages/bokning-av-idrottsutrymmen',
  '/priser': '/sv/pages/priser',
  // English locale versions
  '/library-exercise': '/en/articles/seniors/make-exercise-a-routine-for-yourself-join-the-library-exercise-for-seniors',
  '/children-and-families': '/en/pages/target-groups/children-and-families',
  '/youth': '/en/pages/target-groups/youth',
  '/adults': '/en/pages/target-groups/adults',
  '/seniors': '/en/pages/target-groups/seniors',
  '/adapted-groups': '/en/pages/target-groups/adapted-groups',
  '/partners/en': '/en/pages/target-groups/partners',
  '/easysport/en': '/en/pages/target-groups/children-and-families/easysport',
  '/vimmasports/en': '/en/pages/target-groups/youth/vimma-sports',
  '/funaction/en': '/en/pages/target-groups/youth/vimma-sports',
  '/pages/target-groups/youth/funaction': '/en/pages/target-groups/youth/vimma-sports',
  '/nyt-liikunta/en': '/en/pages/target-groups/youth/nyt-liikunta',
  '/regional-exercise-services': '/en/pages/guided-exercise/regional-exercise-services',
  '/guided-exercise': '/en/pages/guided-exercise',
  '/park-exercise-sessions': '/en/pages/guided-exercise/park-exercise-sessions',
  '/seniorisapinat/en': '/en/pages/target-groups/seniors/seniorisapinat',
  '/special-swimming-card': '/en/pages/support-for-physical-activity/special-swimming-card',
  '/fitness-testing': '/en/pages/support-for-physical-activity/fitness-testing',
  '/fitness-programmes': '/en/pages/support-for-physical-activity/personal-fitness-programmes-and-guidance-at-gyms',
  '/physical-activity-counselling': '/en/pages/support-for-physical-activity/physical-activity-counselling',
  '/liikuntaluuri-telephone-service': '/en/pages/support-for-physical-activity/liikuntaluuri-telephone-service',
  '/sports-sessions': '/en/pages/target-groups/children-and-families/liikuntahulinat-sports-sessions',
  '/family-sports-sessions': '/en/pages/target-groups/children-and-families/perhehulinat-family-sports-sessions-self-guided',
  '/reservation-of-sports-facilities': '/en/pages/reservation-of-sports-facilities',
  '/pricing': '/en/pages/pricing',
};

module.exports = redirectRoutes;
