// Ignore prettier in order to preserve readability of the routes:
// prettier-ignore
const redirectRoutes = {
  // Finnish locale versions
  '/lapset-ja-perheet': '/fi/pages/kohderyhmat/lapset-ja-perheet',
  '/nuoret': '/fi/pages/kohderyhmat/nuoret',
  '/aikuiset': '/fi/pages/kohderyhmat/aikuiset',
  '/ikaantyneet': '/fi/pages/kohderyhmat/ikaantyneet',
  '/soveltavat-ryhmat': '/fi/pages/kohderyhmat/soveltavat-ryhmat',
  '/kumppanit': '/fi/pages/kohderyhmat/kumppanit',
  '/easysport': '/fi/pages/liikuntapalvelut/easysport',
  '/funaction': '/fi/pages/liikuntapalvelut/funaction',
  '/nytliikunta': '/fi/pages/liikuntapalvelut/nyt-liikunta',
  '/alueliikunta': '/fi/pages/liikuntapalvelut/alueliikunta',
  '/ohjattu-liikunta': '/fi/pages/liikuntapalvelut/ohjattu-liikunta',
  '/puistojumpat': '/fi/pages/liikuntapalvelut/ohjattu-liikunta/puistojumpat',
  '/seniorisapinat': '/fi/pages/liikuntapalvelut/seniorisapinat',
  '/erityisuimakortti': '/fi/pages/liikuntapalvelut/erityisuimakortti',
  '/kuntotestaus': '/fi/pages/liikuntapalvelut/kuntotestaus',
  '/kuntosaliohjelmat': '/fi/pages/liikuntapalvelut/kuntosaliohjelmien-laadinta-ja-opastus',
  '/liikuntaneuvonta': '/fi/pages/liikuntapalvelut/liikuntaneuvonta',
  '/liikuntaluuri': '/fi/pages/liikuntapalvelut/liikuntaluuri',
  '/liikuntahulinat': '/fi/pages/liikuntapalvelut/liikuntahulinat',
  '/perhehulinat': '/fi/pages/liikuntapalvelut/perhehulinat-omatoiminen',
  '/liikuntatilavaraukset': '/fi/pages/kohderyhmat/kumppanit/liikuntatilojen-varaaminen',
  '/maksut': '/fi/pages/liikuntapalvelut/maksut-ja-hinnasto',
  // Swedish locale versions
  '/barn-och-familjer': '/sv/sidor/malgrupper/barn-och-familjer',
  '/unga': '/sv/pages/malgrupper/unga',
  '/vuxna': '/sv/pages/malgrupper/vuxna',
  '/aldre': '/sv/pages/malgrupper/aldre',
  '/tillampade-grupper': '/sv/pages/malgrupper/tillampande-grupper',
  '/partners': '/sv/pages/malgrupper/partners/sv',
  '/easysport/sv': '/sv/pages/stod-for-motion/easysport',
  '/funaction/sv': '/sv/pages/stod-for-motion/funaction',
  '/nyt-motion': '/sv/pages/stod-for-motion/nyt-motion',
  '/forortsmotion': '/sv/pages/stod-for-motion/forortsmotion',
  '/handledd-motion': '/sv/pages/stod-for-motion/handledd-motion',
  '/parkgymnastiken': '/sv/sidor/stod-for-motion/handledd-motion/parkgymnastiken',
  '/seniorisapinat/sv': '/sv/pages/stod-for-motion/seniorisapinat',
  '/specialsimkort': '/sv/pages/stod-for-motion/specialsimkort',
  '/konditionstest': '/sv/pages/stod-for-motion/konditionstest',
  '/gymprogram': '/sv/pages/stod-for-motion/handledning-och-utarbetande-av-ett-gymprogram',
  '/motionsradgivning': '/sv/pages/stod-for-motion/motionsradgivning',
  '/motionsluren': '/sv/pages/stod-for-motion/liikuntaluuri-motionsluren',
  '/idrottslek': '/sv/pages/stod-for-motion/liikuntahulinat-idrottslek',
  '/idrottslek-for-familjer': '/sv/pages/stod-for-motion/perhehulinat-idrottslek-for-familjer-pa-egen-hand',
  '/bokning-av-idrottsutrymmen': '/sv/sidor/malgrupper/partners/bokning-av-idrottsutrymmen',
  '/priser': '/sv/sidor/stod-for-motion/priser',
  // English locale versions
  '/children-and-families': '/en/pages/target-groups/children-and-families',
  '/youth': '/en/pages/target-groups/youth',
  '/adults': '/en/pages/target-groups/adults',
  '/seniors': '/en/pages/target-groups/seniors',
  '/adapted-groups': '/en/pages/target-groups/adapted-groups',
  '/partners/en': '/en/pages/target-groups/partners',
  '/easysport/en': '/en/pages/support-for-physical-activity/easysport',
  '/funaction/en': '/en/pages/support-for-physical-activity/funaction',
  '/nyt-liikunta/en': '/en/pages/support-for-physical-activity/nyt-liikunta',
  '/regional-exercise-services': '/en/pages/support-for-physical-activity/regional-exercise-services',
  '/guided-exercise': '/en/pages/support-for-physical-activity/guided-exercise',
  '/park-exercise-sessions': '/en/pages/support-for-physical-activity/guided-exercise/park-exercise-sessions',
  '/seniorisapinat/en': '/en/pages/support-for-physical-activity/seniorisapinat',
  '/special-swimming-card': '/en/pages/support-for-physical-activity/special-swimming-card',
  '/fitness-testing': '/en/pages/support-for-physical-activity/fitness-testing',
  '/fitness-programmes': '/en/pages/support-for-physical-activity/personal-fitness-programmes-and-guidance-at-gyms',
  '/physical-activity-counselling': '/en/pages/support-for-physical-activity/physical-activity-counselling',
  '/liikuntaluuri-telephone-service': '/en/pages/support-for-physical-activity/liikuntaluuri-telephone-service',
  '/sports-sessions': '/en/pages/support-for-physical-activity/liikuntahulinat-sports-sessions',
  '/family-sports-sessions': '/en/pages/support-for-physical-activity/perhehulinat-family-sports-sessions-self-guided',
  '/reservation-of-sports-facilities': '/en/pages/target-groups/partners/reservation-of-sports-facilities',
  '/pricing': '/en/pages/support-for-physical-activity/pricing',
};

module.exports = redirectRoutes;
