federation_version: 2
subgraphs:
  cms:
    routing_url: 'https://tapahtumat.hkih.stage.geniem.io/graphql'
    schema:
      subgraph_url: 'https://tapahtumat.hkih.stage.geniem.io/graphql'
  # events:
  #   routing_url: "https://tapahtumat-proxy.test.kuva.hel.ninja/proxy/graphql"
  #   schema:
  #     subgraph_url: "https://tapahtumat-proxy.test.kuva.hel.ninja/proxy/graphql"
