# Continuous integration (CI) triggers cause a pipeline to run whenever you push
# an update to the specified branches or you push specified tags.
trigger:
  batch: true
  branches:
    include:
      - main
  paths:
    exclude:
    - '*release-please*'
    - '*.md'
    - '.github/'
    - 'pipelines/liikunta-ui-release.yml'
    - 'pipelines/liikunta-ui-review.yml'
    - '*compose*'

# Pull request (PR) triggers cause a pipeline to run whenever a pull request is
# opened with one of the specified target branches, or when updates are made to
# such a pull request.
#
# GitHub creates a new ref when a pull request is created. The ref points to a
# merge commit, which is the merged code between the source and target branches
# of the pull request.
#
# Opt out of pull request validation
pr: none

# By default, use self-hosted agents
pool: Default

resources:
  repositories:
    # Azure DevOps repository
    - repository: liikunta-pipelines
      type: git
      ref: refs/heads/ansible_automation_update
      # Azure DevOps project/repository
      name: liikunta/liikunta-pipelines

extends:
  # Filename in Azure DevOps Repository
  template: components/liikunta-ui/pipelines/liikunta-ui-dev.yml@liikunta-pipelines
  # parameters:
    # Application build arguments and config map values as key value pairs.
    # Does not contain all buildArguments or configMap values, the rest located in liikunta-pipelines
    # The values here will override the values defined in the liikunta-pipelines repository
    # buildArgs:
    #   DEBUG: 1
    # configMap: # pod environment variables
    #   DEBUG: 1
