#
# Review pipeline. Run build and deploy for Platta dev environments.
# Pipeline runs different tests e.g. unittest and browser tests.
#
# Continuous integration (CI) triggers cause a pipeline to run whenever you push
# an update to the specified branches or you push specified tags.
# only PR trigger pipeline
trigger: none

# Pull request (PR) triggers cause a pipeline to run whenever a pull request is
# opened with one of the specified target branches, or when updates are made to 
# such a pull request.
#
# GitHub creates a new ref when a pull request is created. The ref points to a 
# merge commit, which is the merged code between the source and target branches 
# of the pull request.
#
# Opt out of pull request validation 
pr:
  # PR target branch
  branches:
    include:
    - main
  paths:
    exclude:
    - '*release-please*'
    - '*.md'
    - '.github/'
    - 'pipelines/tapahtumat-ui-release.yml'
    - 'pipelines/tapahtumat-ui-dev.yml'
    - '*compose*'

# By default, use self-hosted agents
pool: Default

resources:
  repositories:
    # Azure DevOps repository
    - repository: tapahtumat-pipelines
      type: git
      ref: refs/heads/ansible_automation_update
      # Azure DevOps project/repository
      name: tapahtumat/tapahtumat-pipelines

extends:
  # Filename in Azure DevOps Repository
  template: components/tapahtumat-ui/pipelines/tapahtumat-ui-review.yml@tapahtumat-pipelines
  parameters:
    # Application build arguments and config map values as key value pairs.
    # Does not contain all buildArguments, the rest located in tapahtumat-pipelines/tapahtumat-variables-development.yml and tapahtumat-variables-common.yml
    # The values here will override the values defined in the tapahtumat-pipelines repository
    buildArgs:
      FEDERATION_ROUTER_ENDPOINT: https://events-graphql-federation-events.dev.hel.ninja/
      CMS_ORIGIN: https://tapahtumat.app-staging.hkih.hion.dev
      LINKEDEVENTS_EVENT_ENDPOINT: https://api.hel.fi/linkedevents/v1/event
      NEXTJS_DISABLE_SENTRY: 0
      NEXT_PUBLIC_ALLOW_UNAUTHORIZED_REQUESTS: 1
      NEXT_PUBLIC_DEBUG: 1
      NEXT_PUBLIC_MATOMO_ENABLED: 0
    configMap: # pod environment variables
      FEDERATION_ROUTER_ENDPOINT: https://events-graphql-federation-events.dev.hel.ninja/
      CMS_ORIGIN: https://tapahtumat.app-staging.hkih.hion.dev
      LINKEDEVENTS_EVENT_ENDPOINT: https://api.hel.fi/linkedevents/v1/event
