name: CI-Hobbies-Helsinki

on:
  push:
    branches: [main]
    # Only consider those paths to trigger the action
    paths:
      - 'apps/hobbies-helsinki/**'
      - 'packages/components/**'
      - 'packages/common-i18n/**'
      - '.yarnrc.yml'
      - 'tsconfig.base.json'
      - '.prettier*'
      - '.github/workflows/**'

  pull_request:
    branches: [main]
    # Only consider those paths to trigger the action
    paths:
      - 'apps/hobbies-helsinki/**'
      - 'packages/components/**'
      - 'packages/common-i18n/**'
      - '.yarnrc.yml'
      - 'tsconfig.base.json'
      - '.prettier*'
      - '.github/workflows/**'
  workflow_dispatch:

env:
  env_federation_router_endpoint: https://events-graphql-federation-hobbies.test.hel.ninja/
  env_cms_origin: https://harrastus.app-staging.hkih.hion.dev
  env_linkedevents_event_endpoint: https://api.hel.fi/linkedevents/v1/event

jobs:
  common:
    uses: City-of-Helsinki/.github/.github/workflows/ci-node.yml@ci_node_parameters
    secrets: inherit
    with:
      node-version: 20
      typecheck: true
      app-directory: apps/hobbies-helsinki
      extra-commands: |
        echo "ENABLE_ADMIN_APP=true" >> $GITHUB_ENV
        echo "ENABLE_REDIRECT_APP=true" >> $GITHUB_ENV
        # Speed up build: they are linted in a previous step
        echo "NEXTJS_IGNORE_ESLINT=true" >> $GITHUB_ENV
        # Speed up build: they are typechecked in a previous step
        echo "NEXTJS_IGNORE_TYPECHECK=true" >> $GITHUB_ENV
        # Speed up build: don't run if not needed, enable if it becomes needed
        echo "NEXT_DISABLE_SOURCEMAPS=true" >> $GITHUB_ENV
        # Don't send telemetry for ci
        echo "NEXT_TELEMETRY_DISABLED=true" >> $GITHUB_ENV
        # To allow checking size-limits
        echo "NEXTJS_DISABLE_SENTRY=false" >> $GITHUB_ENV
        # Fully disable sentry upload
        echo "NEXTJS_SENTRY_UPLOAD_DRY_RUN=true" >> $GITHUB_ENV
        echo "FEDERATION_ROUTER_ENDPOINT=$env_federation_router_endpoint" >> $GITHUB_ENV
        echo "CMS_ORIGIN=$env_cms_origin" >> $GITHUB_ENV
        echo "LINKEDEVENTS_EVENT_ENDPOINT=$env_linkedevents_event_endpoint" >> $GITHUB_ENV
        # Mock origin
        echo "NEXT_PUBLIC_APP_ORIGIN=https://localhost:3001" >> $GITHUB_ENV
        echo "NEXT_PUBLIC_MATOMO_URL_BASE=//webanalytics.digiaiiris.com/js/" >> $GITHUB_ENV
        echo "NEXT_PUBLIC_MATOMO_SITE_ID=939" >> $GITHUB_ENV
        echo "NEXT_PUBLIC_MATOMO_SRC_URL=piwik.min.js" >> $GITHUB_ENV
        echo "NEXT_PUBLIC_MATOMO_TRACKER_URL=tracker.php" >> $GITHUB_ENV
        echo "NEXT_PUBLIC_MATOMO_ENABLED=0" >> $GITHUB_ENV

  # build: 
  #   name: Lint and build
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       node-version: [20.x]
  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Use Node.js ${{ matrix.node-version }}
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: ${{ matrix.node-version }}
  #         cache: 'yarn'

  #     - name: Install dependencies
  #       run: |
  #         yarn install --immutable --inline-builds
  #       env:
  #         HUSKY: 0

  #     - name: Build web-app
  #       working-directory: apps/hobbies-helsinki
  #       run: |
  #         yarn build
  #       env:
  #         # Speed up build: they are linted in a previous step
  #         NEXTJS_IGNORE_ESLINT: true
  #         # Speed up build: they are typechecked in a previous step
  #         NEXTJS_IGNORE_TYPECHECK: true
  #         # Speed up build: don't run if not needed, enable if it becomes needed
  #         NEXT_DISABLE_SOURCEMAPS: true
  #         # Don't send telemetry for ci
  #         NEXT_TELEMETRY_DISABLED: true
  #         # To allow checking size-limits
  #         NEXTJS_DISABLE_SENTRY: false
  #         # Fully disable sentry upload
  #         NEXTJS_SENTRY_UPLOAD_DRY_RUN: true
  #         FEDERATION_ROUTER_ENDPOINT: ${{env.FEDERATION_ROUTER_ENDPOINT}}
  #         CMS_ORIGIN: ${{env.CMS_ORIGIN}}
  #         LINKEDEVENTS_EVENT_ENDPOINT: ${{env.LINKEDEVENTS_EVENT_ENDPOINT}}
  #         # Mock origin
  #         NEXT_PUBLIC_APP_ORIGIN: https://localhost:3001
  #         NEXT_PUBLIC_MATOMO_URL_BASE: '//webanalytics.digiaiiris.com/js/'
  #         NEXT_PUBLIC_MATOMO_SITE_ID: 939
  #         NEXT_PUBLIC_MATOMO_SRC_URL: 'piwik.min.js'
  #         NEXT_PUBLIC_MATOMO_TRACKER_URL: 'tracker.php'
  #         NEXT_PUBLIC_MATOMO_ENABLED: 0

  #     - name: Check browser bundle size limits
  #       working-directory: apps/hobbies-helsinki
  #       run: |
  #         yarn check-size

  #     - name: Check ecmascript checks for build files
  #       working-directory: apps/hobbies-helsinki
  #       run: |
  #         yarn check-dist

  # test:
  #   name: Test
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       node-version: [20.x]
  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Use Node.js ${{ matrix.node-version }}
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: ${{ matrix.node-version }}
  #         cache: 'yarn'

  #     - name: Install dependencies
  #       run: |
  #         yarn install --immutable --inline-builds
  #       env:
  #         HUSKY: 0

  #     - name: Typecheck
  #       working-directory: apps/hobbies-helsinki
  #       run: |
  #         yarn typecheck

  #     - name: Linter
  #       working-directory: apps/hobbies-helsinki
  #       run: |
  #         yarn lint

  #     - name: Unit tests
  #       working-directory: apps/hobbies-helsinki
  #       run: |
  #         yarn test:coverage
  #       env:
  #         TZ: Europe/Helsinki
  #         FEDERATION_ROUTER_ENDPOINT: ${{env.FEDERATION_ROUTER_ENDPOINT}}
  #         CMS_ORIGIN: ${{env.CMS_ORIGIN}}
  #         LINKEDEVENTS_EVENT_ENDPOINT: ${{env.LINKEDEVENTS_EVENT_ENDPOINT}}
  #         # Mock origin
  #         NEXT_PUBLIC_APP_ORIGIN: https://localhost:3001

  #     - name: SonarQube Cloud Scan
  #       uses: SonarSource/sonarqube-scan-action@v5.1.0
  #       with:
  #         projectBaseDir: apps/hobbies-helsinki
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

