name: Hobbies Helsinki Build & Staging
on:
  push:
    branches:
      - main

# allow only one run at a time
concurrency: ${{ github.workflow }}

env:
  CONTAINER_REGISTRY: ghcr.io
  CONTAINER_REGISTRY_USER: ${{ secrets.GHCR_CONTAINER_REGISTRY_USER }}
  CONTAINER_REGISTRY_PASSWORD: ${{ secrets.GHCR_TOKEN }}
  CONTAINER_REGISTRY_REPO: ghcr.io/city-of-helsinki/${{ github.event.repository.name }}
  KUBECONFIG_RAW: ${{ secrets.KUBECONFIG_RAW_STAGING }}
  BUILD_ARTIFACT_FOLDER: 'build_artifacts'
  SERVICE_ARTIFACT_FOLDER: 'service_artifacts'
  BASE_DOMAIN: ${{ secrets.BASE_DOMAIN_STAGING }}
  SERVICE_PORT: 3000
  PROJECT: hobbies-helsinki
  K8S_REQUEST_CPU: 50m
  K8S_REQUEST_RAM: 150Mi
  K8S_LIMIT_CPU: 200m
  K8S_LIMIT_RAM: 400Mi
  # horizontal pod autoscaler
  K8S_HPA_ENABLED: true
  K8S_HPA_MAX_REPLICAS: 3
  K8S_HPA_MIN_REPLICAS: 1
  K8S_HPA_MAX_CPU_AVG: 80 # 80% from request
  #  K8S_HPA_MAX_RAM_AVG: 80 # 80% from request

  K8S_LIVENESS_PATH: /api/healthz
  K8S_READINESS_PATH: /api/readiness
  NEXT_PUBLIC_SENTRY_ENVIRONMENT: 'test'
  NEXT_PUBLIC_SENTRY_DSN: ${{ secrets.GH_SENTRY_DSN }}
  NEXT_PUBLIC_SENTRY_TRACE_SAMPLE_RATE: 0
  NEXTJS_DISABLE_SENTRY: 1
  SENTRY_AUTH_TOKEN: ${{ secrets.GH_SENTRY_AUTH_TOKEN }}
  NEXT_PUBLIC_CMS_GRAPHQL_ENDPOINT: https://events-graphql-router-hobbies.kuva.hel.ninja/
  NEXT_PUBLIC_EVENTS_GRAPHQL_ENDPOINT: https://events-graphql-router-hobbies.kuva.hel.ninja/
  NEXT_PUBLIC_LINKEDEVENTS_EVENT_ENDPOINT: https://api.hel.fi/linkedevents/v1/event
  NEXT_PUBLIC_MATOMO_URL_BASE: '//webanalytics.digiaiiris.com/js/'
  NEXT_PUBLIC_MATOMO_SITE_ID: 939
  NEXT_PUBLIC_MATOMO_SRC_URL: 'piwik.min.js'
  NEXT_PUBLIC_MATOMO_TRACKER_URL: 'tracker.php'
  NEXT_PUBLIC_MATOMO_ENABLED: 0
  NEXT_PUBLIC_APP_ORIGIN: https://${{ secrets.ENVIRONMENT_URL_STAGING_HARRASTUKSET }}

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v2
      - name: Build
        uses: andersinno/kolga-build-action@v2
        env:
          DOCKER_IMAGE_NAME: ${{ env.PROJECT }}-staging
          DOCKER_BUILD_ARG_APP_PORT: ${{ env.SERVICE_PORT }}
          DOCKER_BUILD_ARG_PROJECT: ${{ env.PROJECT }}
          DOCKER_BUILD_ARG_SENTRY_AUTH_TOKEN: ${{ secrets.GH_SENTRY_AUTH_TOKEN }}
          DOCKER_BUILD_ARG_NEXT_PUBLIC_DEBUG: 1
          DOCKER_BUILD_ARG_NEXTJS_DISABLE_SENTRY: ${{env.NEXTJS_DISABLE_SENTRY}}
          DOCKER_BUILD_ARG_NEXT_PUBLIC_CMS_GRAPHQL_ENDPOINT: ${{ env.NEXT_PUBLIC_CMS_GRAPHQL_ENDPOINT }}
          DOCKER_BUILD_ARG_NEXT_PUBLIC_EVENTS_GRAPHQL_ENDPOINT: ${{ env.NEXT_PUBLIC_EVENTS_GRAPHQL_ENDPOINT }}
          DOCKER_BUILD_ARG_NEXT_PUBLIC_LINKEDEVENTS_EVENT_ENDPOINT: ${{ env.NEXT_PUBLIC_LINKEDEVENTS_EVENT_ENDPOINT }}
          DOCKER_BUILD_ARG_NEXT_PUBLIC_APP_ORIGIN: ${{ env.NEXT_PUBLIC_APP_ORIGIN }}
          DOCKER_BUILD_ARG_NEXT_PUBLIC_MATOMO_URL_BASE: ${{ env.NEXT_PUBLIC_MATOMO_URL_BASE }}
          DOCKER_BUILD_ARG_NEXT_PUBLIC_MATOMO_SITE_ID: ${{ env.NEXT_PUBLIC_MATOMO_SITE_ID }}
          DOCKER_BUILD_ARG_NEXT_PUBLIC_MATOMO_SRC_URL: ${{ env.NEXT_PUBLIC_MATOMO_SRC_URL }}
          DOCKER_BUILD_ARG_NEXT_PUBLIC_MATOMO_TRACKER_URL: ${{ env.NEXT_PUBLIC_MATOMO_TRACKER_URL }}
          DOCKER_BUILD_ARG_NEXT_PUBLIC_MATOMO_ENABLED: ${{ env.NEXT_PUBLIC_MATOMO_ENABLED }}
          DOCKER_BUILD_ARG_NEXT_PUBLIC_ALLOW_UNAUTHORIZED_REQUESTS: 1
          DOCKER_BUILD_ARG_NEXT_PUBLIC_SENTRY_ENVIRONMENT: 'staging'
          DOCKER_BUILD_ARG_NEXT_PUBLIC_SENTRY_DSN: ${{ secrets.GH_SENTRY_DSN }}
          DOCKER_BUILD_ARG_NEXT_PUBLIC_SENTRY_TRACE_SAMPLE_RATE: ${{ env.NEXT_PUBLIC_SENTRY_TRACE_SAMPLE_RATE }}
  staging:
    runs-on: ubuntu-latest
    needs: build
    name: Staging and Accept
    steps:
      - uses: actions/checkout@v2
      - uses: andersinno/kolga-setup-action@v2

      - name: Deploy
        uses: andersinno/kolga-deploy-action@v2
        with:
          track: 'staging'
        env:
          K8S_NAMESPACE: ${{ secrets.K8S_NAMESPACE_STAGING_HARRASTUKSET }}
          ENVIRONMENT_URL: https://${{ secrets.ENVIRONMENT_URL_STAGING_HARRASTUKSET }}
          ENVIRONMENT_SLUG: ${{ env.PROJECT }}
          DOCKER_IMAGE_NAME: ${{ env.PROJECT }}-staging
          K8S_SECRET_NEXT_PUBLIC_CMS_GRAPHQL_ENDPOINT: ${{ env.NEXT_PUBLIC_CMS_GRAPHQL_ENDPOINT }}
          K8S_SECRET_NEXT_PUBLIC_EVENTS_GRAPHQL_ENDPOINT: ${{ env.NEXT_PUBLIC_EVENTS_GRAPHQL_ENDPOINT }}
          K8S_SECRET_NEXT_PUBLIC_LINKEDEVENTS_EVENT_ENDPOINT: ${{ env.NEXT_PUBLIC_LINKEDEVENTS_EVENT_ENDPOINT }}
          K8S_SECRET_NEXT_PUBLIC_APP_ORIGIN: ${{ env.CUSTOM_ENVIRONMENT_URL }}
          K8S_SECRET_NEXT_PUBLIC_ALLOW_UNAUTHORIZED_REQUESTS: 1
          K8S_SECRET_NEXT_PUBLIC_DEBUG: 1
          K8S_SECRET_APP_PORT: ${{ env.SERVICE_PORT }}
          K8S_SECRET_PROJECT: ${{ env.PROJECT }}
          PROJECT: ${{ env.PROJECT }}

      # browser tests
      - name: Setup Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 16.x
      - name: Create yarn cache directory path
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        run: yarn install --immutable
      - name: Run Acceptance Tests
        id: testcafe
        working-directory: apps/hobbies-helsinki
        run: yarn test:browser:ci
        env:
          BROWSER_TESTS_ENV_URL: https://${{ secrets.ENVIRONMENT_URL_STAGING_HARRASTUKSET }}
      - name: Upload screenshots and videos of failed tests to artifact
        uses: actions/upload-artifact@v2
        with:
          name: report
          path: ./report
        if: always() && steps.testcafe.outcome == 'failure'
