name: Events Apollo Router Staging

on:
  push:
    branches:
      - main
    paths:
      - 'proxies/events-graphql-federation/subgraphs/**'
      - '!**/README.md'

env:
  CONTAINER_REGISTRY: ghcr.io
  CONTAINER_REGISTRY_USER: ${{ secrets.GHCR_CONTAINER_REGISTRY_USER }}
  CONTAINER_REGISTRY_PASSWORD: ${{ secrets.GHCR_TOKEN }}
  CONTAINER_REGISTRY_REPO: ghcr.io/city-of-helsinki/${{ github.event.repository.name }}
  KUBECONFIG_RAW: ${{ secrets.KUBECONFIG_RAW }}
  BUILD_ARTIFACT_FOLDER: 'build_artifacts'
  SERVICE_ARTIFACT_FOLDER: 'service_artifacts'
  BASE_DOMAIN: ${{ secrets.BASE_DOMAIN_STAGING }}
  K8S_REQUEST_CPU: 50m
  K8S_REQUEST_RAM: 150Mi
  K8S_LIMIT_CPU: 200m
  K8S_LIMIT_RAM: 400Mi
  SERVICE_PORT: 8088
  K8S_LIVENESS_PATH: /health
  K8S_READINESS_PATH: /health
  REPO_NAME: ${{ github.event.repository.name }}

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v3
      - name: Build
        uses: andersinno/kolga-build-action@v2
        env:
          DOCKER_BUILD_SOURCE: ./proxies/events-graphql-federation/Dockerfile
          DOCKER_BUILD_CONTEXT: ./proxies/events-graphql-federation

  staging:
    strategy:
      fail-fast: false
      matrix:
        service: ['events', 'hobbies']
        include:
          - service: 'events'
            FEDERATION_CMS_ROUTING_URL: https://tapahtumat.hkih.stage.geniem.io/graphql
            FEDERATION_EVENTS_ROUTING_URL: https://tapahtumat-proxy.test.kuva.hel.ninja/proxy/graphql
            FEDERATION_UNIFIED_SEARCH_ROUTING_URL: https://unified-search.test.kuva.hel.ninja/search
          - service: 'hobbies'
            FEDERATION_CMS_ROUTING_URL: https://harrastus.hkih.stage.geniem.io/graphql
            FEDERATION_EVENTS_ROUTING_URL: https://tapahtumat-proxy.test.kuva.hel.ninja/proxy/graphql
            FEDERATION_UNIFIED_SEARCH_ROUTING_URL: https://unified-search.test.kuva.hel.ninja/search

    runs-on: ubuntu-latest
    needs: build
    # allow only one deployment at a time
    concurrency: ${{ github.workflow }}-${{ github.head_ref }}
    name: Staging and Accept
    steps:
      - uses: actions/checkout@v2
      - uses: andersinno/kolga-setup-action@v2
      - name: Deploy ${{ matrix.service}}
        uses: andersinno/kolga-deploy-action@v2
        env:
          ENVIRONMENT_URL: https://events-graphql-federation-${matrix.service}.${{env.BASE_DOMAIN}}
          ENVIRONMENT_SLUG: router-${{ matrix.service }}
          K8S_SECRET_FEDERATION_CMS_ROUTING_URL: ${{ matrix.FEDERATION_CMS_ROUTING_URL }}
          K8S_SECRET_FEDERATION_EVENTS_ROUTING_URL: ${{ matrix.FEDERATION_EVENTS_ROUTING_URL }}
          K8S_SECRET_FEDERATION_UNIFIED_SEARCH_ROUTING_URL: ${{ matrix.FEDERATION_UNIFIED_SEARCH_ROUTING_URL }}
          # K8S_SECRET_ROUTER_HEALTHCHECK_URL: https://${{env.K8S_NAMESPACE}}-${{ matrix.service }}.${{ env.BASE_DOMAIN }}
