name: Events Apollo Router Review

on:
  push:
    branches:
      - main
    paths:
      - 'proxies/events-graphql-router/subgraphs/**'
      - '!**/README.md'

  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - 'proxies/events-graphql-router/subgraphs/**'
      - '!**/README.md'

env:
  CONTAINER_REGISTRY: ghcr.io
  CONTAINER_REGISTRY_USER: ${{ secrets.GHCR_CONTAINER_REGISTRY_USER }}
  CONTAINER_REGISTRY_PASSWORD: ${{ secrets.GHCR_TOKEN }}
  CONTAINER_REGISTRY_REPO: ghcr.io/city-of-helsinki/${{ github.event.repository.name }}
  KUBECONFIG_RAW: ${{ secrets.KUBECONFIG_RAW }}
  BUILD_ARTIFACT_FOLDER: 'build_artifacts'
  SERVICE_ARTIFACT_FOLDER: 'service_artifacts'
  BASE_DOMAIN: ${{ secrets.BASE_DOMAIN_STAGING }}
  K8S_REQUEST_CPU: 50m
  K8S_REQUEST_RAM: 150Mi
  K8S_LIMIT_CPU: 200m
  K8S_LIMIT_RAM: 400Mi
  SERVICE_PORT: 4000
  K8S_LIVENESS_PATH: /health
  K8S_READINESS_PATH: /health
  REPO_NAME: ${{ github.event.repository.name }}

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v3
      - name: Build
        uses: andersinno/kolga-build-action@v2
        env:
          DOCKER_BUILD_SOURCE: ./proxies/events-graphql-router/Dockerfile
          DOCKER_BUILD_CONTEXT: ./proxies/events-graphql-router

  review:
    strategy:
      fail-fast: false
      matrix:
        service: ['events', 'hobbies']
        include:
          - service: 'events'
            ROUTER_CMS_ROUTING_URL: https://tapahtumat.hkih.stage.geniem.io/graphql
            ROUTER_EVENTS_ROUTING_URL: https://tapahtumat-proxy.test.kuva.hel.ninja/proxy/graphql
            ROUTER_UNIFIED_SEARCH_ROUTING_URL: https://unified-search.test.kuva.hel.ninja/search
          - service: 'hobbies'
            ROUTER_CMS_ROUTING_URL: https://harrastus.hkih.stage.geniem.io/graphql
            ROUTER_EVENTS_ROUTING_URL: https://tapahtumat-proxy.test.kuva.hel.ninja/proxy/graphql
            ROUTER_UNIFIED_SEARCH_ROUTING_URL: https://unified-search.test.kuva.hel.ninja/search

    runs-on: ubuntu-latest
    needs: build
    # allow only one deployment at a time
    concurrency: ${{ github.workflow }}-${{ github.head_ref }}
    name: Graphql-Router Review & Acceptance Tests for ${{ matrix.service }}
    steps:
      - uses: actions/checkout@v2
      - uses: andersinno/kolga-setup-action@v2
      - name: Deploy ${{ matrix.service }}
        uses: andersinno/kolga-deploy-action@v2
        env:
          ENVIRONMENT_URL: https://${{env.K8S_NAMESPACE}}-${{ matrix.service }}.${{ env.BASE_DOMAIN }}
          ENVIRONMENT_SLUG: router-${{ matrix.service }}
          K8S_SECRET_ROUTER_CMS_ROUTING_URL: ${{ matrix.ROUTER_CMS_ROUTING_URL }}
          K8S_SECRET_ROUTER_EVENTS_ROUTING_URL: ${{ matrix.ROUTER_EVENTS_ROUTING_URL }}
          K8S_SECRET_ROUTER_UNIFIED_SEARCH_ROUTING_URL: ${{ matrix.ROUTER_UNIFIED_SEARCH_ROUTING_URL }}
          # K8S_SECRET_ROUTER_HEALTHCHECK_URL: https://${{env.K8S_NAMESPACE}}-${{ matrix.service }}.${{ env.BASE_DOMAIN }}
      - name: Setup kubectl
        run: |
          echo "${{ env.KUBECONFIG_RAW }}" > $(pwd)/kubeconfig
          echo "KUBECONFIG=$(pwd)/kubeconfig" >> $GITHUB_ENV
        shell: bash
      - name: Get Review Deploy URL for version ${{ matrix.version }}
        id: deploy-url
        run: |
          DEPLOY_URL=$(kubectl get ingress "router-${{ matrix.service }}-${{env.REPO_NAME}}-ingress" -n ${{env.K8S_NAMESPACE}} -o jsonpath='{.spec.rules[0].host}')
          echo "BROWSER_TESTS_LOCAL_ENV_URL=https://$DEPLOY_URL" >> $GITHUB_ENV
        shell: bash
      - name: Create PR comment for service ${{ matrix.service }}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          header: router-deployment-${{ matrix.service }}
          message: |
            **Events-Graphql-Router for ${{ matrix.service }} is deployed to: ${{ env.BROWSER_TESTS_LOCAL_ENV_URL }}** :rocket::rocket::rocket:
            _NOTE: the changes to the apps are still reviewed against the staging environment, which does not have the changes yet._
