name: CI-Venue-Graphql-Proxy

on:
  push:
    branches: [main]
    # Only consider those paths to trigger the action
    paths:
      - 'proxies/venue-graphql-proxy/**'
      - '.yarnrc.yml'
      - 'tsconfig.base.json'
      - '.prettier*'
      - '.github/workflows/ci-venue-graphql-proxy-check.yml'

  pull_request:
    branches: [main]
    # Only consider those paths to trigger the action
    paths:
      - 'proxies/venue-graphql-proxy/**'
      - '.yarnrc.yml'
      - 'tsconfig.base.json'
      - '.prettier*'
      - '.github/workflows/ci-venue-graphql-proxy-check.yml'
  workflow_dispatch:

jobs:
  common:
    uses: City-of-Helsinki/.github/.github/workflows/ci-node.yml@ci_working_directory
    secrets: inherit
    with:
      node-version: 20
      typecheck: true
      app-directory: proxies/venue-graphql-proxy
      extra-commands: |
        echo "NODE_ENV=production" >> $GITHUB_ENV
        echo "GRAPHQL_PROXY_DEBUG=debug" >> $GITHUB_ENV
        echo "GRAPHQL_PROXY_PORT=4100" >> $GITHUB_ENV
        echo "GRAPHQL_PROXY_SENTRY_ENVIRONMENT=local" >> $GITHUB_ENV
        echo "GRAPHQL_PROXY_DISABLE_WINSTON_LOGGING=0" >> $GITHUB_ENV
        echo "GRAPHQL_PROXY_INTROSPECTION=1" >> $GITHUB_ENV
        # events proxy only
        echo "GRAPHQL_PROXY_MAP_OPEN_DATA_API_BASE_URL=https://kartta.hel.fi/ws/geoserver/avoindata" >> $GITHUB_ENV
        echo "GRAPHQL_PROXY_API_BASE_URL=https://api.hel.fi/linkedevents/v1/" >> $GITHUB_ENV
